---
all:
  children:
    homelab:
      hosts:
        homelab-1:
          ansible_host: homelab-1  # Update with the IP or network hostname to connect as
          ansible_user: daniel
          ansible_become: yes
          ansible_python_interpreter: /usr/bin/python3
