---
all:
  children:
    homelab:
      hosts:
        homelab-1:
          ansible_host: 192.168.1.36  # Update with your HP EliteDesk IP
          ansible_user: daniel
          ansible_become: yes
