---
- name: Create restic backup storage directory
  file:
    path: /backup-data/restic-backups
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0700'
  become: true