---
- name: restart samba
  systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    # smbd: Samba daemon for file sharing
    # nmbd: NetBIOS name server daemon for network browsing
    - smbd
    - nmbd