$ANSIBLE_VAULT;1.1;AES256
38613134386133636634303964306639373938653137386233636235363732643233346366383230
3566616265386166613934343038363134316136376436650a663362353534663261356666616132
35666430353262643332306235373239303735663661623463363038373162626431646438653263
6136313465366362390a383638343038383266323364383863646137623266613636653262366365
30613737336462396132663334303438383734643464386365366539336133316332373334323138
66613465373736643239356538313839616535656638636239336465366433663834393132356539
33373462313138313939313439636334393861336464663061356162343330336661663031633330
30323161623135656333333865653238396664366664633333616439616331613664343165623231
64656231316362646463336639343564633563326566613333303236306139613133663138333039
3832313532356136373361316562633564636236333866386436
