$ANSIBLE_VAULT;1.1;AES256
31313539643434306632623236663735633863633738613564363864626535653639663362353832
3739353863643864323466353466306438623063303765320a323838663730356637363535663963
30666635363963646135313634623162303330643334303935303664613963366334376335623136
3063386132336166380a653661353035613436636564376536373631623461333031643339346137
35346338353130343366353636353164633539383362373661353061343432613231656636326465
31666632323062363030303935636132343439666438666465643265663235366431366464636166
37383163336465363637326330363938363230616662616535363664303737626435323334343863
34316364396337346636313536303631653635643338663036623630306234306163343439376337
3233
