---
- name: restart docker
  systemd:
    name: docker
    state: restarted
  become: true

- name: reload zfs modules
  shell: |
    modprobe -r zfs
    modprobe zfs
  become: true

- name: reload systemd
  systemd:
    daemon_reload: yes
  become: true