---
- name: Create Docker data directory
  file:
    path: /opt/docker-data
    state: directory
    owner: "{{ ansible_user }}"
    group: docker
    mode: '0755'

- name: Create Docker networks
  docker_network:
    name: "{{ item }}"
    state: present
  loop:
    - homelab-network